# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
yarn_mappings=1.21+build.2
loader_version=0.15.11

# Mod Properties
mod_version=3.0.2+1.21
maven_group=com.mikolajkolek
archives_base_name=fix-alt-gr

# Dependencies
jnativehook_version=2.2.2
